import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Epilogue } from "next/font/google";
import { cn } from "@/lib/utils";
import "./globals.css";


export const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
})

export const epilogue = Epilogue({
  subsets: ["latin"],
  variable: "--font-epilogue",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
        "min-h-screen bg-background font-sans antialiased",
        inter.variable
      )}>{children}</body>
    </html>
  );
}
